### PR TITLE
Sous with Recipes

### PR DESCRIPTION
**Pull request by laura-johnson**
**Description:**

Add the basic framework to apply a recipe and add a basic recipe.

## Recipe update

**To run setup + install:**
1. `lando start`
2. `lando composer install`
3. `composer run-script post-create-project-cmd` 

There is one recipe currently:

**sous_base:** 
- scaffolded from /assets within the project 
- assigns the emulsify theme as the main theme
- creates a superuser role and assigns admin permissions

The following unpacks the composer dependencies to the main composer file so that we can remove the recipe 
`lando composer unpack fourkitchens/[recipe_name]`

Note: we may want to automate this process of installing/unpacking/removing - maybe add it to the install-recipe script (TBD).

### Composer update
1. Removed the normal Sous Drupal dependencies
2. Upgraded to Drupal 10
3. Added patch that allows recipes to be applied
5. Added post update script to scaffold recipes from assets to web/recipes (scripts/recipe-scaffold.sh)

### Assets
1. Added sous_base recipe with scaffolding that adds the recipe to web/recipes on install

### Scripts
1. Added script that installs a recipe using lando (scripts/install-recipe.sh)
2. Modified setups.sh script to install the Minimal profile without existing config (we will use recipes to install config)
3. Modified sous/Starter.php script to rewrite the theme name in the recipe to match the installed theme

### Lando
1. Added command that installs a recipe using a script (see above)

### CODE REVIEW

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@laura-johnson I hit some roadblocks on this one but in general this is a really great start/direction to take Sous. I still need to audit our modules and configuration fully which would affect this PR but the following items could be addressed now:

- I had to add manually add Sous Builder to the repositories section before I could run `lando composer require fourkitchens/sous-builder:dev-sous-content-recipe` Here is the change I made: ```"repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        },
        {
            "type": "vcs",
            "url": "https://gitlab.ewdev.ca/yonas.legesse/drupal-recipe-unpack.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/fourkitchens/sous-builder.git"
        }
    ],```
- Running the `lando install-recipe sous-builder` fails due to a conflict with the superuser role config `The configuration 'user.role.superuser' exists already and does not match the recipe's configuration`
- The Metatag module needs a version bump to `^2` in this PR so it matches the version in the recipe.
- Per our first Sous checkin meeting with the ROCK team I think we move the following configuration back to this main project branch.
    - `config/default/system.action.user_add_role_action.superuser.yml`
    -  config/default/system.action.user_remove_role_action.superuser.yml
    - All config associated with Media
    - The text format filters (these probably need to be updated for CKEdtior5)
    - Gin settings

**Comment by laura-johnson** [comment]
@callinmullaney based on our more recent work, I removed the instruction to install the sous_builder recipe. We'll add a sous_media module to get the media config rather than have it in a config directory - maybe the media recipe contains the text format filters. Your sous_admin recipe will add config for Gin. I altered the sous_base recipe so that it only installs what is required for core and also for emulsify (component and emulsify_twig).  It also contains config for the superuser role.

config/default/system.action.user_add_role_action.superuser.yml config/default/system.action.user_remove_role_action.superuser.yml

Those are generated automatically when the superuser role is created and they get exported with the first drush config-export.

**Review by robert-arias — APPROVED** [review]
:shipit:

**Pull request merged**
