### PR TITLE
Scaffold

### PR DESCRIPTION
**Pull request by ccjjmartin**
1. Fix why this isn't appending additions-default.settings.txt to settings.php.
2. Verify that you can pick default config during the Sous install.

### CODE REVIEW

**Comment by cbfannin** [comment]
@heatherwoz @laura-johnson @ccjjmartin

What do you think about using a patch to make this work?

The `append` approach wouldn't work because the settings.php file wouldn't exist yet since that runs pre site install. Similarly the solution we came up with during contrib hours to edit the default.settings.php file directly wouldn't work because we aren't tracking the web directory. I could have copied the entire default.settings.php file to our assets/scaffold/files directory, made the changes to that file, and scaffolded the entire thing but then we are maintaining an entire settings file and not getting Drupal's updates. Now that I write this out I am thinking this is what I was supposed to do ...

The way I ended up doing it was through a patch file. During composer install the default.settings.php file is patched with our changes. When the site install happens it copies that file with our patches applied.

I wonder if updating the patch every time Drupal changes the default.settings.php file would get annoying.

If this way sucks let me know and I will do it the other way ... the way I was probably meant to do it to begin with :)~

**Comment by laura-johnson** [comment]
Can we append the lines to default.settings.php?

**Comment by cbfannin** [comment]
@laura-johnson Are you saying that is the way I should do it rather than the patch way? Or are you asking If we can use composer `append` key? I don't think we can use composer's `append` because the file won't exist yet. I think we either have to store our own default.settings.php file in our own scaffolding folder and scaffold it over during composer install or do a patch post install.

Unless I am just not understanding ... which is quite possible.

**Comment by cbfannin** [comment]
@laura-johnson My apologies. As I mentioned on Slack every time default.settings.php was mentioned my brain kept translating that to settings.php for some reason. This is now set back to Chris' original approach and targeting default.settings.php rather than settings.php. I ran it once and it worked as expected.

@ccjjmartin apologies for jacking up your branch ... but we have default settings now :)~

**Pull request merged**
