### PR TITLE
docs(readme): update documentation for contribution without create-project

### PR DESCRIPTION
**Pull request by ccjjmartin**
## Purpose:
- A dev might want to create their own project with a custom theme name or have some other custom install process they want to follow, so let's show them now to install the project from scratch.
- This also allows for better testing of the emulsify-cli directly

## Testing:
- Read and follow the readme section that this PR adds.

### CODE REVIEW

**Comment by callinmullaney** [comment]
@ccjjmartin added some suggestions. I agree with your slack message that someone less familiar with the project should test/approve this PR. Nice work!

**Comment by ccjjmartin** [comment]
I will need to work on this again since I updated it to be based on the 4.x branch.

**Comment by ccjjmartin** [comment]
@callinmullaney Where are your suggestions?

**Comment by ccjjmartin** [comment]
@rebecaescandon The info shown during `npx emulsify init theme-name` doesn't need any actions during Sous setup (I double checked but the composer require stuff is already declared in the emulsify theme so we don't have to double declare it).

In regards to your white screen, there could be a lot of reasons why it didn't show up but my guess might be that you were using lando and had another copy of the sous project installed somewhere and didn't destroy it before starting up this instance of it.  Since the screen is completely blank it probably is showing a "successful" homepage to you.  If you create a .lando.local.yml you can add this info to it to create a new instance of the site and that should allow you to install things properly without deleting the old one:

```
name: sous-project-docs-test
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://sous-project-docs-test.lndo.site"
      XDEBUG_SESSION: 1
```

Or if you don't want to change the name, a `lando destroy` at the very beginning of the process should get rid of the old instance of `sous-project`

**Pull request merged**
